#!/bin/sh
set -eu

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" "${MYSQL_DATABASE}" <<SQL
CREATE USER IF NOT EXISTS '${MYSQL_APP_USER}'@'%' IDENTIFIED BY '${MYSQL_APP_PASSWORD}';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.\`rets_property\` TO '${MYSQL_APP_USER}'@'%';
FLUSH PRIVILEGES;
SQL
